repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        stages: [commit]
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        stages: [commit]
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        stages: [commit]
-   repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [--rcfile=.pylintrc, --recursive=y]
        exclude: (migrations)
        stages: [push]
