service: lambda-mongodb-scraping-data
frameworkVersion: '3'

provider:
  name: aws
  region: us-west-2
  stage: dev

  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  extract_data_from_playlatam:
    timeout: 900
    memorySize: 2048
    image:
      name: img